Remove enforceTimeLimit attribute
The feature needs to install additional package.

    Error: Package phpunit/php-invoker is required for enforcing time limits